### ISSUE TITLE
TypeScript type safety

### ISSUE THREAD

**Issue by felixfbecker** [apollographql/graphql-tag#138]
Currently `gql` just returns `any`.
Type safety would be very helpful for
- manipulating the returned AST
- type safety for query execution functions (ensuring only an AST is passed)
- moving an existing application from string queries to the string tag

graphql-tag should have `@types/graphql` as a dependency and return a Document

**Comment by jnwng** [comment]
@felixfbecker im not super familiar with TypeScript — it sounds like you know what needs to be done to get this to work properly though. im happy to accept a PR to this effect!

**Comment by samuela** [comment]
What's the status with this? I'm seeing errors when using graphql-tag 2.10.0 in TypeScript:
```
index.ts:67:15 - error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("/Users/skainswo/dev/kumo/bobthebuilder/node_modules/graphql-tag/index")' has no compatible call signatures.

 67     mutation: gql`
                  ~~~~
 68       mutation SendReleaseStatusEvent($releaseID: String!, $status: String!) {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
 72       }
    ~~~~~~~
 73     `,
    ~~~~~

error Command failed with exit code 2.
```

**Comment by samuela** [comment]
Update: correct TS import is `import gql from "graphql-tag";`.

**Comment by Samox** [comment]
Hey guys, I'm seeing an `any` type on the gql objects.
![image](https://user-images.githubusercontent.com/6906559/64683202-1b940300-d483-11e9-9714-6f9965cb2431.png)

Do you know how to properly type it ?

**Comment by Wintus** [comment]
As far as I dig through the issues, the return type specification was reverted in #218 (again) due to the problem of #150.

current master:
https://github.com/apollographql/graphql-tag/blob/50a850e484a60d95ddb99801c39785031e55b7a2/index.d.ts#L1

Since it is typed as `any`, I don't think proper typing can be done without downcast.

**Comment by PabloSzx** [comment]
I made a library that strongly types **graphql-tag** and allows to inject the type expected in the tag itself, improving functions like **useQuery**.

Since the [type safety was reverted](https://github.com/jnwng/graphql-tag/commit/51f178f7b4a55fa616f60d49264658a565c8ac11), people lurking around here might find it useful.

[graphql-tag-ts](https://github.com/PabloSzx/graphql-tag-ts)
