### ISSUE TITLE
Add a cli to precompile gql files to typescript 

### ISSUE THREAD

**Issue by leiserfg** [apollographql/graphql-tag#147]
In angular is a big problem to use custom webpack loaders. I'am thinking in somethink like pug-cli.

**Comment by jnwng** [comment]
this might help you: https://github.com/apollographql/graphql-tag#typescript

**Comment by klemenoslaj** [comment]
@jnwng, I think this is still a very valid request because in fact your proposed solution is still falling in the same trap/problem @leiserfg mentioned -> no custom webpack loaders in Angular CLI(_which is sad_).

`ts-transform-graphql-tag` seems to be working only with FuseBox or with webpack on top of 2 most popular TypeScript loaders `ts-loader` and `awesome-typescript-loader` and neither of them is used by Angular CLI.

Having some other alternative to pre-build GraphQL files or `gql` tags in TypeScript would help Angular community quite a bit(_currently not possible_).
