### ISSUE TITLE
GraphQL mutation, parameters / variables objects (with dot notation)

### ISSUE THREAD

**Issue by johnunclesam** [apollographql/graphql-tag#149]
I have a Graphql Mutation like this:

gql query:

```
mutation UpdateMother($mother_id: ID!, $child_name: String!) {
  updateMother(
    mother: {
      id: $id
      child: {
        name: $child_name
      }
    }
  )
}
```

It works good, but I need to use `$child.name` instead of `$child_name`. Is this possible?

**Comment by jnwng** [comment]
@johnunclesam unfortunately GraphQL doesn't really make any distinctions on the things that are passed to it — you would just pass `$child.name` to begin with and add that as a variable.

in any case, this is a question that should go in [graphql/graphql-js](https://github.com/graphql/graphql-js) as part of the GraphQL specification, this library merely wraps that one.

**Comment by johnunclesam** [comment]
`$child.name` doesn't work.

**Comment by jnwng** [comment]
@johnunclesam yes, because property access is not part of the GraphQL specification. instead of doing property access in GraphQL, pass the variable that you want to use:

```graphql
mutation SomeMutation($child_name: String!) {
  fooMutation(name: $child_name) 
}
```

when you invoke this query, pass the child_name as a variable:
```js
request(graphqlQuery, {
  variables: {
    child_name: child.name
  }
})
```
so you can get around the property access.

fyi — passing arguments to things like mutation normally involves parentheses like the example i provided. i'd expect your mutation to look like:

```graphql
mutation UpdateMother($mother_id: ID!, $child_name: String!) {
  updateMother(
    mother(id: $mother_id): {
      child(name: $child_name) {
        name
      }
    }
  )
}
```
although this is a little contrived since you already have the child name to begin with. does that makes sense?
