### ISSUE TITLE
Support more advanced cache strategy

### ISSUE THREAD

**Issue by kimiyang** [apollographql/graphql-tag#182]
**Issue Labels**

- [ ] has-reproduction
- [x] feature
- [ ] docs
- [ ] blocking
- [ ] good first issue

We are trying to use graphql-tag(gt) in our production, but found one problem, since gt only use a simple object as cache, and the cache keeps growing if every time the query is different, and the memory use will be a problem if we have millions of different queries. We hope that gt can support a more advanced cache strategy, such as LRU, so that we can control the size of the cache and better manage the memory use. In some cases we even don't want to have cache. Actually I have implemented this feature in my fork with node-lru-cache. I'm not sure if I can submit a PR and this can be incorporated into the gt core library?@jnwng

**Comment by edokeh** [comment]
+1

**Comment by hotoo** [comment]
Good idea.

**Comment by LiJiakai** [comment]
this is a severe problem, and if this is the truth, I will doubt whether to use in prod

**Comment by Ross-Jo** [comment]
+1

**Comment by jnwng** [comment]
@kimiyang in order to have a more objective approach to this, it would be useful to get a benchmark that we can use to measure the impact of using something like `node-lru-cache` here. i dont have an accurate sense of how this is going to impact the library and it's usage.

just a couple of constraints that would be helpful for me to get this in:
1) establish a benchmark that we can use to measure all future work here so that we're not regressing
2) make sure this works well in browsers, since `graphql-tag` is pushed to the client.
3) is this something we can optionally add as an advanced usage since i suspect many people don't have millions of queries?

to make my workload a little more manageable, im going to close this issue for now. please re-open if the above two things make sense as a path forward!
