### ISSUE TITLE
(invalid?) warning appears when reusing the same fragment inside a single query

### ISSUE THREAD

**Issue by iambumblehead** [apollographql/graphql-tag#269]
This query,
```javascript
export const GET_CONTENT = gql`
fragment LanguageData on ContentInternationalization {
    id
    language
    title
    description
}

query getContent ( $contentId: UUID! ) {
    content( id: $contentId ) {
        primaryLanguage {
            ...LanguageData
        }
        languages {
            ...LanguageData
        }
    }
}`;
```
Results in this warning message,
```
Warning: fragment with name LanguageData already exists.
graphql-tag enforces all fragment names across your application to be unique;
read more about this in the docs:
http://dev.apollodata.com/core/fragments.html#unique-names
```

I'm not sure if the warning is valid and/or I'm not sure how best to change my query to satisfy graphql-tag.

**Comment by jnwng** [comment]
we have a global module cache ( https://github.com/apollographql/graphql-tag/blob/1fd2c9d0378163d76b8091dd2dbd3afc6142a34a/src/index.js#L15 ) of the fragments we parse — that means that somewhere else in your application, there's another fragment defined with the same name. we protect against this because if you were to interpolate both of them into the same GraphQL document, it would fail validation.

you can disable this warning by invoking disableFragmentWarnings ( https://github.com/apollographql/graphql-tag#warnings )

**Comment by tafelito** [comment]
@jnwng can you elaborate more on your answer? There is no way to find anywhere in the docs what's the issue with this

I know I can disable the warning, but I want to know if I should disable or what is the issue if I don't

I run 2 queries in the same page and both access the same fragment, so what is the correct way of doing that? I'm not naming 2 different fragments with the same name, is 2 queries with the same fragment, is not the same thing
