### ISSUE TITLE
Move Webpack Loader to its own repository

### ISSUE THREAD

**Issue by jtmthf** [apollographql/graphql-tag#32]
I've been working on the included webpack loader to add support for `@import` directives and am thinking that it could be worth moving the loader to its own repository. Beyond `@import` support I have some ideas for adding options and using the loader as a tool to incorporate persisted queries and custom scalars. As the loader becomes more complex and feature-rich, it could be worth moving to its own repository.

**Comment by stubailo** [comment]
Just a heads up - @poincare is working on the exact same thing right now. I do agree that it might be worth moving the loader out.

**Comment by Poincare** [comment]
@jtmthf Agree with moving it into a separate repo eventually, just not until I get #33 merged :) 

By the way, #33 implements "#import" as a set of comments since it is simpler than having to parse the actual AST of the query and pick out "@import" directives. There's also the [extractgql](https://github.com/Poincare/extractgql), which is meant for persisted query support and currently provides middleware for Express as well as a persisted query network interface for Apollo Client. It is a bit undocumented right now, but that will be fixed soon.

**Comment by stubailo** [comment]
I think once we validate `#import` having an `@import` directive on fragments would be a great next step! It could work in a very similar way.

**Comment by jnwng** [comment]
@Poincare any updates on this? are there blockers that need to be addressed?

**Comment by jnwng** [comment]
going to close this — please re-open if we think this needs to be separated.
