### ISSUE TITLE
type in .grapgql file

### ISSUE THREAD

**Issue by cd-ducle** [apollographql/graphql-tag#333]
![image](https://user-images.githubusercontent.com/72440368/104404399-2ab22600-558d-11eb-85dc-900db907dd92.png)
![image](https://user-images.githubusercontent.com/72440368/104404498-61883c00-558d-11eb-83b4-342af5cd9096.png)
Hello everyone. I have a problem with type declare in .graphql file.  It seems to be a syntax error. Can anybody show me the solution for this case ? Thank you so much.

**Comment by jerelmiller** [comment]
Hey @cd-ducle 👋 

From what I understand, The `input` type you're declaring here is not necessary. The GraphQL schema itself will define that type, so your mutation declaration should be all thats needed.

Try removing the `input CartItem` and see if that improves things.

**Comment by jerelmiller** [comment]
Hey @cd-ducle 👋 

The issue here is that your `input` type is trying to use JS object syntax as its type for the `data` field, but its expecting a type name instead. For nested objects, GraphQL syntax expects that it would be set to another input type:

```
input CartItem {
  data: CartItemData
}

input CartItemData {
  quantity: Float!
  sku: String!
}
```

This should fix the error since that `data` field now properly reflects its type.

---

That being said, your screenshot seems to have a mix of both query and schema SDL syntax. `input` types are typically defined at the schema level by your server. This isn't declared in client code for your queries/mutations. I'd recommend removing the `input` from your `graphql` document here. You might get some strange errors from your GraphQL server otherwise.

I'm going to close this issue for now, but feel free to reopen if you need more help. Hope this helps!
