### ISSUE TITLE
[Bug] Dynamically Assembled Queries === Memory Leak

### ISSUE THREAD

**Issue by mmmeff** [apollographql/graphql-tag#356]
The document cache employed by this package [uses a plain `Map`](https://github.com/apollographql/graphql-tag/blob/main/src/index.ts#L10) with zero regard for its growth and memory footprint.

If a user creates queries dynamically for any reason, this can cause the size of the Map to grow endlessly. This is manifesting as a memory leak in production for my team as we assemble dynamic queries based on several variables driven by a highly-entropic dataset.

Switching to `node-lru` and exposing configuration options to limit the memory footprint of the document cache would be a good mechanism to prevent users from running into this issue. Sane defaults could apply here as well - perhaps limit the size of the document cache to 64MB by default.

**Comment by macrozone** [comment]
> The document cache employed by this package [uses a plain `Map`](https://github.com/apollographql/graphql-tag/blob/main/src/index.ts#L10) with zero regard for its growth and memory footprint.
> 
> If a user creates queries dynamically for any reason, this can cause the size of the Map to grow endlessly. This is manifesting as a memory leak in production for my team as we assemble dynamic queries based on several variables driven by a highly-entropic dataset.
> 
> Switching to `node-lru` and exposing configuration options to limit the memory footprint of the document cache would be a good mechanism to prevent users from running into this issue. Sane defaults could apply here as well - perhaps limit the size of the document cache to 64MB by default.

i am not a maintainer, but i noticed that you said "If a user creates queries dynamically for any reason". Graphql queries usually contain variables for the dynamic part in the template literal, so the size of your queries in your application should be fixed. Its also possible to pre-compile graphql tags using https://www.npmjs.com/package/babel-plugin-graphql-tag that of course only works if you are using graphql-tag as intended (with literals).

**Comment by mmmeff** [comment]
@macrozone 

> the size of your queries in your application should be fixed

Says who? 

We've already fixed the query generation in our application to use variables, but this is a huge footgun. On a large team with engineers of varying levels of expertise, it's very hard to say this won't happen again on a rapidly growing project. I recommend you familiarize yourself with [the pit of success.](https://blog.codinghorror.com/falling-into-the-pit-of-success/) The most widely adopted and loved libraries follow this principle. 

Along those lines, I'd be open to revising this PR to make LRU cache the default behavior. Disarming footguns with sane defaults is always a better strategy than undocumented good intentions.

**Comment by macrozone** [comment]
> Says who?

Well...

- https://stackoverflow.com/a/54838939/1463534 says that you should avoid string interpolation to create dynamic queries refering to the spec
- The spec indeed says so: https://graphql.org/learn/queries/
- Vscode extensions for graphql syntax throws a syntax error when you try to do string interpolation (exception: adding fragments on top level)
- Apollo server and the studio also assumes that every query has a well defined name. Dynamic queries might interfere with response caching or other caching layers

I know the pit of success, I would say i depends here on whether this use case (dynamic constructing queries) is an intended or not. **If** not (as hinted by the graphql specs and apollo toolings), the documentation should say so (or the library should warn if it detects such a use (probably tricky)). So let's see what contributers have to say about this

**Comment by benjamn** [comment]
@mmmeff Your input is welcome, but you're overselling it. Please drop the condescending, over-generalizing tone.

@macrozone is right that using a relatively fixed/stable set of queries in your application is encouraged across the GraphQL ecosystem. If you end up with many megabytes of parsed queries over time, that's almost certainly a bug that won't be meaningfully solved by putting an arbitrary limit on the cache size. I imagine you won't like the phrase "almost certainly a bug" because I don't know your specific use cases, but my experience suggests parsed `DocumentNode` objects will be a relatively small part of your memory/performance problems if you're really using that many different queries.

You can already call [`resetCaches`](https://github.com/apollographql/graphql-tag/blob/e48e47dee5949acbab86b75dae156be480c4063c/src/index.ts#L136-L139) to clear the map, which has the drawback of re-parsing future queries, giving `!==` document objects. If you're okay with LRU eviction, you are either not too concerned about those drawbacks (because eviction has similar drawbacks, just less predictably), or you're assuming (without any guarantee) that infrequently used queries are actually never going to be used again, so there's no harm in evicting them. If someone really wants to be sure they always get the same (`===`) `DocumentNode` for a given query string, I'm not sure it's the business of this library to question how many queries they ask it to parse, beyond supporting the escape hatch of resetting the cache with `resetCaches`.

However, I do see two areas for further improvement here:
* A simpler LRU mechanism that doesn't add a new dependency.
  * The `docCache` map has only one access point, so I believe these changes could be mostly confined within [`parseDocument`](https://github.com/apollographql/graphql-tag/blob/e48e47dee5949acbab86b75dae156be480c4063c/src/index.ts#L93-L110).
  * You could take advantage of JavaScript's [reliable ordering of `Map` keys](https://tc39.es/ecma262/#sec-map.prototype.foreach) to maintain the LRU list "for free," provided you bump each key (upon access) to the front of the list by removing it and re-adding it.
  * If you think the `sizeOfCacheEntry` logic is critical, I would suggest using just the size of the query _string_ as an approximate estimate of relative query size, rather than recursively scanning the `DocumentNode` object (which is also approximate, after all).
* A finer-grained cache that's capable of sharing immutable sub-documents between multiple parsed queries, rather than just caching whole queries, significantly reducing the total memory usage of many parsed queries that have sub-structures in common.
  * This is trickier because it may require changes to the parser itself, and it complicates `sizeOfCacheEntry`-style logic because cache entries are no longer completely separate from one another.

**Comment by mmmeff** [comment]
Don't know why you feel the need to make this personal. I'm sorry you dislike my tone, but I'd prefer to talk about the merit of this PR than your feelings.

I disagree with the sentiment that "dependencies === bad", and this PR explicitly does the diligence of making this a proper peer dependency that users can opt into. I don't see the point in reimplementing an LRU cache from scratch inside of this library. Feels very "not invented here" to me.

**Comment by mmmeff** [comment]
Furthermore, your second point of adding a finer grained cache is completely compatible with an LRU cache and is a good idea, but feels out of scope for this specific issue.

**Comment by benjamn** [comment]
A gentle reminder to be professional in a professional space is not a personal attack. I'm sure you'd prefer to change the subject back to code when you're called out for bad interpersonal behavior—and I'm happy to do so—but I do expect open-source collaborators to be respectful of one another, regardless of whatever technical merit they think they have on their side.

I was excited momentarily by your claim that the `lru-cache` dependency is optional, because I'd missed that in my first glance at your PR, but I'm afraid the way you've done it does not really make the dependency optional, because the `graphql-tag` package will be broken if its users do not also run `npm i lru-cache` (as you explain in your README changes), which means `lru-cache` is effectively a non-optional dependency that has to be installed manually, by every developer using `graphql-tag` or any of its dependent packages. From my perspective as a maintainer, that's even worse than adding an ordinary direct dependency.

I did not say dependencies are bad, and that's not a reasonable subtext to read into my previous comment. This package happens to have only one dependency at the moment, [`tslib`](https://www.npmjs.com/package/tslib), and I see real value in holding the line against bundle size increases due to unnecessary new dependencies. If this codebase was an application with a large number of dependencies already, I would happily reach for a tried-and-true package with as many downloads as `lru-cache`, but `graphql-tag` is intended to be tiny package with a very specific purpose.

Even if I secretly love reinventing things, as you seem to be suggesting by referring to NIH syndrome, that's only an observation, not a disqualifying objection. In fact, I'll give you that one. I believe we can do a better job implementing this functionality entirely within this package.

**Comment by mmmeff** [comment]
You are single handedly the most toxic individual I have ever interfaced with on Github. I'm trying to help out here and you're spitting in my face.

**Comment by mmmeff** [comment]
Keep your shitty library with its shitty unbounded map memory leaks. I'll just fork you and move along with my day. I don't have time to debate semantics with you.

**Comment by macrozone** [comment]
well that escalated quickly... 

@benjamn thank you for your calm and constructive answers.

One question: should constructing queries based on non-literals be discouraged? If so, maybe that should be highlighted somewhere in the docs (more obvious than now). I guess its hard for the library (graphql-tag) to detect such usages, but maybe offer an alternative api (a function call or so) that does not cache the result at all for use with fully dynamic queries (so caching would be done in userland)?

**Comment by foreverest** [comment]
We're using `graphql-tag` to parse user queries incoming into our API so we can't really control what users send to us or encourage the users to use variables. This is currently a big problem for us and we would definitely benefit of a LRU/LFU cache here.
