### ISSUE TITLE
Feature request: Loader could validate the query against the schema.

### ISSUE THREAD

**Issue by vangorra** [apollographql/graphql-tag#90]
Since we are already compiler the query into AST. It would be great if we could validate the query against a schema.graphqls or schema json file.
Thoughts?

**Comment by jnwng** [comment]
@vangorra [eslint-plugin-graphql](https://github.com/apollographql/eslint-plugin-graphql) will do this for you at compile time, which i think is more preferable than waiting until runtime with `graphql-tag`. is that a suitable solution?

**Comment by vangorra** [comment]
@jnwng I was proposing the webpack loader performs these checks as it compiles the graphql to AST during build time. While the eslint looks great, I'm not sure it would help here as it is specific to JS and not also typescript. By building the check into the webpack loader, things become language agnostic.

**Comment by inakianduaga** [comment]
This webpack loader

https://www.npmjs.com/package/webpack-graphql-loader

actually supports this feature, and it works correctly BUT it has a bug and doesn't parse introspection responses correctly (doesn't like the root "data" node, works if you remove the top root data node). 

Since the code is not on github it's not easy to fix the project.

**Comment by vangorra** [comment]
@inakianduaga Nice find. Just implemented it. The webpack-graphql-loader module will work best.
